<a href="https://colab.research.google.com/github/eunjoo-ny/ML-Code/blob/main/2_PyTorch_Lab_07__Tensor_Manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Multivariate Linear Regression review\\
Minbatch Gradient Descent theory\\
PyTorch Dataset and DataLoader method\\

In [ ]:
from torch.utils.data import Dataset

class CustomDataset(Dataset):
      def __init__(self):
          self.x_data=[[73,80,75],
                     [93,88,93],
                     [89,91,90],
                     [96,98,100],
                     [73,66,70]]
          self.y_data=[[152],[185],[180],[196],[142]]


      def __len__(self):
          return len(self.x_data)

      def __getitem__(self,idx):
          x=torch.FloatTensor(self.x_data[idx])
          y=torch.FloatTensor(self.y_data[idx])
          return x,y




In [ ]:
dataset=CustomDataset()

In [ ]:
import os
import torch
import torchvision
import tarfile
from torchvision.datasets.utils import download_url
from torch.utils.data import random_split
from torch.utils.data import DataLoader
from torch.nn import functional as F
import torch.nn as nn 
import torch.optim as optim 

In [ ]:
x_train=torch.FloatTensor([[73,80,756],
                           [93,88,93],
                           [89,91,90],
                           [96,98,100],
                           [73,66,70]])
y_train=torch.FloatTensor([[152],[185],[180],[196],[142]])
import torch.nn as nn
class MultivaritateLinearRegression(nn.Module):
      def __init__(self):
          super().__init__()
          self.linear=nn.Linear(3,1)

      def forward(self,x):
          return self.linear(x)
model=MultivaritateLinearRegression()

In [ ]:


dataloader=DataLoader(
    dataset,
    batch_size=2,
    shuffle=True,
)

In [ ]:
nb_epochs=20
for epoch in range(nb_epochs+1):
    for batch_idx, samples in enumerate(dataloader):
        x_train, y_train=samples
        model=MultivaritateLinearRegression()
        prediction=model(x_train)

        cost=F.mse_loss(prediction,y_train)
        optimizer=optim.SGD(model.parameters(), lr=0.01, momentum=0.9)

        optimizer.zero_grad()
        cost.backward()
        optimizer.step()


        print("Epoch: {:4d}/{}, Batch:{}/{} , Cost:{:.6f}".format(epoch,nb_epochs, batch_idx, len(dataloader),
                                                                  cost.item()))

Epoch:    0/20, Batch:0/3 , Cost:33404.011719
Epoch:    0/20, Batch:1/3 , Cost:33400.441406
Epoch:    0/20, Batch:2/3 , Cost:60513.515625
Epoch:    1/20, Batch:0/3 , Cost:38455.476562
Epoch:    1/20, Batch:1/3 , Cost:32038.042969
Epoch:    1/20, Batch:2/3 , Cost:43189.605469
Epoch:    2/20, Batch:0/3 , Cost:30776.562500
Epoch:    2/20, Batch:1/3 , Cost:42684.250000
Epoch:    2/20, Batch:2/3 , Cost:9899.545898
Epoch:    3/20, Batch:0/3 , Cost:23779.812500
Epoch:    3/20, Batch:1/3 , Cost:48281.488281
Epoch:    3/20, Batch:2/3 , Cost:53133.078125
Epoch:    4/20, Batch:0/3 , Cost:37895.679688
Epoch:    4/20, Batch:1/3 , Cost:48244.640625
Epoch:    4/20, Batch:2/3 , Cost:14937.728516
Epoch:    5/20, Batch:0/3 , Cost:21311.740234
Epoch:    5/20, Batch:1/3 , Cost:70698.921875
Epoch:    5/20, Batch:2/3 , Cost:29969.396484
Epoch:    6/20, Batch:0/3 , Cost:32812.109375
Epoch:    6/20, Batch:1/3 , Cost:13609.546875
Epoch:    6/20, Batch:2/3 , Cost:33036.281250
Epoch:    7/20, Batch:0/3 , Cost:46

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim


In [ ]:
#for reproducibility
torch.manual_seed(1)

In [ ]:
x_data=[[1,2],[2,3],[3,1],[4,3],[5,3],[6,2]]
y_data=[[0],[0],[0],[1],[1],[1]]
x_data_test=[[2,3],[4,2],[5,3]]
y_data_test=[[0],[1],[1]]

In [ ]:
x_train=torch.FloatTensor(x_data)
y_train=torch.FloatTensor(y_data)
x_test=torch.FloatTensor(x_data_test)
y_test=torch.FloatTensor(y_data_test)

In [ ]:
print(x_train.shape)
print(y_train.shape)

torch.Size([6, 2])
torch.Size([6, 1])


In [ ]:
print('e^1 equals: ',torch.exp(torch.FloatTensor([1])))

e^1 equals:  tensor([2.7183])


In [ ]:
w=torch.zeros((2,1), requires_grad=True)
b=torch.zeros(1, requires_grad=True)

In [ ]:
hypothesis= 1/(1+torch.exp(-(x_train.matmul(w)+b)))

In [ ]:
print(hypothesis)
print(hypothesis.shape)
print(y_train)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<MulBackward0>)
torch.Size([6, 1])
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.]])


In [ ]:
-(y_train[0]*torch.log(hypothesis[0])+(1-y_train[0])*torch.log(1-hypothesis[0]))

tensor([0.6931], grad_fn=<NegBackward>)

In [ ]:
losses=-(y_train*torch.log(hypothesis)+(1-y_train)*torch.log(1-hypothesis))
print(losses)

tensor([[0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931]], grad_fn=<NegBackward>)


In [ ]:
cost=torch.mean(losses)
print(cost)

tensor(0.6931, grad_fn=<MeanBackward0>)


In [ ]:
F.binary_cross_entropy(hypothesis, y_train)

tensor(0.6931, grad_fn=<BinaryCrossEntropyBackward>)

In [ ]:
w=torch.zeros((2,1), requires_grad=True)
b=torch.zeros(1, requires_grad=True)
optimizer=optim.SGD([w,b],lr=1)

nb_epochs=1000
for epoch in range(nb_epochs+1):

  hypothesis=torch.sigmoid(x_train.matmul(w)+b)
  cost=F.binary_cross_entropy( hypothesis,y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()


  if epoch%100==0:
     print('Epoch:{:4d}/{},cost:{:6f}'.format(epoch, nb_epochs, cost.item()))

Epoch:   0/1000,cost:0.693147
Epoch: 100/1000,cost:0.134722
Epoch: 200/1000,cost:0.080643
Epoch: 300/1000,cost:0.057900
Epoch: 400/1000,cost:0.045300
Epoch: 500/1000,cost:0.037261
Epoch: 600/1000,cost:0.031672
Epoch: 700/1000,cost:0.027556
Epoch: 800/1000,cost:0.024394
Epoch: 900/1000,cost:0.021888
Epoch:1000/1000,cost:0.019852


In [ ]:
hypothesis =torch.sigmoid(x_train.matmul(w)+b)
print(hypothesis[:5])

tensor([[2.7648e-04],
        [3.1608e-02],
        [3.8977e-02],
        [9.5622e-01],
        [9.9823e-01]], grad_fn=<SliceBackward>)


In [ ]:
prediction=hypothesis>=torch.FloatTensor([0.5])
print(prediction[:5])

tensor([[False],
        [False],
        [False],
        [ True],
        [ True]])


In [ ]:
print(y_train[:5])

tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.]])


In [ ]:
correct_prediction=prediction.float()==y_train
print(correct_prediction[:5])

tensor([[True],
        [True],
        [True],
        [True],
        [True]])


In [ ]:
#Higher implementation with Class
class BinaryClassifier(nn.Module):
      def __init__(self):
          super().__init__()
          self.linear=nn.Linear(2,1)
          self.sigmoid=nn.Sigmoid()

      def forward(self,x):
          return self.sigmoid(self.linear(x))

In [ ]:
model=BinaryClassifier()

In [ ]:
optimizer=optim.SGD(model.parameters(), lr=1)

nb_epochs=100
for epoch in range(nb_epochs+1):
    hypothesis=model(x_train)
    cost=F.binary_cross_entropy(hypothesis,y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%20==0:
       prediction=hypothesis>=torch.FloatTensor([0.5])
       correct_prediction=prediction.float()==y_train
       accuracy=correct_prediction.sum().item()/len(correct_prediction)

       print('Epoch:{:4d}/{}, cost:{:.6f}, accuracy:{:2.2f}'.format(epoch, nb_epochs, cost.item(), accuracy))

Epoch:   0/100, cost:1.435795, accuracy:0.50
Epoch:  20/100, cost:0.553339, accuracy:0.83
Epoch:  40/100, cost:0.363422, accuracy:0.83
Epoch:  60/100, cost:0.217145, accuracy:0.83
Epoch:  80/100, cost:0.151170, accuracy:1.00
Epoch: 100/100, cost:0.130686, accuracy:1.00


In [ ]:
import torch
import torch as nn
import torch.nn.functional as F
import torch.optim as optim

In [ ]:
torch.manual_seed(1)

In [ ]:
z=torch.FloatTensor([1,2,3])

In [ ]:
hypothesis=F.softmax(z,dim=0)
print(hypothesis)

tensor([0.0900, 0.2447, 0.6652])


In [ ]:
hypothesis.sum()

tensor(1.)

In [ ]:
y=torch.randint(5,(3,)).long()
print(y)

tensor([3, 3, 3])


In [ ]:
y_one_hot=torch.zeros_like(hypothesis)
y_one_hot.scatter_(1, y.unsqueeze(1),1)

IndexError: ignored