<a href="https://colab.research.google.com/github/eunjoo-ny/ML-Code/blob/main/PyTorch_lab_04_2_load_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
nums=[0,1,2,3,4]

In [ ]:
print(nums)

[0, 1, 2, 3, 4]


In [ ]:
print(nums[2:4])

[2, 3]


In [ ]:
#to get from index2 
print(nums[2:])

[2, 3, 4]


In [ ]:
# to get before2
print(nums[:2])

[0, 1]


In [ ]:
#to get all
print(nums[:])

[0, 1, 2, 3, 4]


In [ ]:
#to get by before last index
print(nums[:-1])

[0, 1, 2, 3]


In [ ]:
nums[2:4]=[8,9]
print(nums)

[0, 1, 8, 9, 4]


In [ ]:
#Slicing 2D array
import numpy as np


In [ ]:
b= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [ ]:
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
#get the second column
print(b[:,1])

[ 2  6 10 14]


In [ ]:
#get the last row
print(b[-1])

[13 14 15 16]


In [ ]:
print(b[-1,:])

[13 14 15 16]


In [ ]:
print(b[-1,...])

[13 14 15 16]


In [ ]:
#get the first and second row
print(b[0:2,:])

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
#xy = np.loadtxt('data-01_2-test-score.csv', delimiter=',', dtype=np.float32)


In [ ]:
new_data={'73':[73],
          '80':[80],
          '75':[75],
          '152':[152]}
new_data1=pd.DataFrame(new_data)
new_data1

73  80  75  152
0  73  80  75  152

In [ ]:
import pandas as pd
data1=pd.read_csv('data-01_2-test-score.csv', error_bad_lines=False)  

data=pd.DataFrame(data1)

#data1.loc[0]=[73,80,75,152]
data1,data

(    73  80   75  152
 0   93  88   93  185
 1   89  91   90  180
 2   96  98  100  196
 3   73  66   70  142
 4   53  46   55  101
 5   69  74   77  149
 6   47  56   60  115
 7   87  79   90  175
 8   79  70   88  164
 9   69  70   73  141
 10  70  65   74  141
 11  93  95   91  184
 12  79  80   73  152
 13  70  73   78  148
 14  93  89   96  192
 15  78  75   68  147
 16  81  90   93  183
 17  88  92   86  177
 18  78  83   77  159
 19  82  86   90  177
 20  86  82   89  175
 21  78  83   85  175
 22  76  83   71  149
 23  96  93   95  192,     73  80   75  152
 0   93  88   93  185
 1   89  91   90  180
 2   96  98  100  196
 3   73  66   70  142
 4   53  46   55  101
 5   69  74   77  149
 6   47  56   60  115
 7   87  79   90  175
 8   79  70   88  164
 9   69  70   73  141
 10  70  65   74  141
 11  93  95   91  184
 12  79  80   73  152
 13  70  73   78  148
 14  93  89   96  192
 15  78  75   68  147
 16  81  90   93  183
 17  88  92   86  177
 18  78  83   77  159
 19  82  8

In [ ]:
new_df=pd.concat([new_data1,data])
new_df

73  80   75  152
0   73  80   75  152
0   93  88   93  185
1   89  91   90  180
2   96  98  100  196
3   73  66   70  142
4   53  46   55  101
5   69  74   77  149
6   47  56   60  115
7   87  79   90  175
8   79  70   88  164
9   69  70   73  141
10  70  65   74  141
11  93  95   91  184
12  79  80   73  152
13  70  73   78  148
14  93  89   96  192
15  78  75   68  147
16  81  90   93  183
17  88  92   86  177
18  78  83   77  159
19  82  86   90  177
20  86  82   89  175
21  78  83   85  175
22  76  83   71  149
23  96  93   95  192

In [ ]:
df=np.array(new_df)
df
df_ten=torch.FloatTensor(df)
df_ten

tensor([[ 73.,  80.,  75., 152.],
        [ 93.,  88.,  93., 185.],
        [ 89.,  91.,  90., 180.],
        [ 96.,  98., 100., 196.],
        [ 73.,  66.,  70., 142.],
        [ 53.,  46.,  55., 101.],
        [ 69.,  74.,  77., 149.],
        [ 47.,  56.,  60., 115.],
        [ 87.,  79.,  90., 175.],
        [ 79.,  70.,  88., 164.],
        [ 69.,  70.,  73., 141.],
        [ 70.,  65.,  74., 141.],
        [ 93.,  95.,  91., 184.],
        [ 79.,  80.,  73., 152.],
        [ 70.,  73.,  78., 148.],
        [ 93.,  89.,  96., 192.],
        [ 78.,  75.,  68., 147.],
        [ 81.,  90.,  93., 183.],
        [ 88.,  92.,  86., 177.],
        [ 78.,  83.,  77., 159.],
        [ 82.,  86.,  90., 177.],
        [ 86.,  82.,  89., 175.],
        [ 78.,  83.,  85., 175.],
        [ 76.,  83.,  71., 149.],
        [ 96.,  93.,  95., 192.]])

In [ ]:
import torch
import torch.nn as nn

In [ ]:
x_data=df_ten[:,0:-1]
x_data


tensor([[ 73.,  80.,  75.],
        [ 93.,  88.,  93.],
        [ 89.,  91.,  90.],
        [ 96.,  98., 100.],
        [ 73.,  66.,  70.],
        [ 53.,  46.,  55.],
        [ 69.,  74.,  77.],
        [ 47.,  56.,  60.],
        [ 87.,  79.,  90.],
        [ 79.,  70.,  88.],
        [ 69.,  70.,  73.],
        [ 70.,  65.,  74.],
        [ 93.,  95.,  91.],
        [ 79.,  80.,  73.],
        [ 70.,  73.,  78.],
        [ 93.,  89.,  96.],
        [ 78.,  75.,  68.],
        [ 81.,  90.,  93.],
        [ 88.,  92.,  86.],
        [ 78.,  83.,  77.],
        [ 82.,  86.,  90.],
        [ 86.,  82.,  89.],
        [ 78.,  83.,  85.],
        [ 76.,  83.,  71.],
        [ 96.,  93.,  95.]])

In [ ]:
y_data=df_ten[:,[-1]]
y_data

tensor([[152.],
        [185.],
        [180.],
        [196.],
        [142.],
        [101.],
        [149.],
        [115.],
        [175.],
        [164.],
        [141.],
        [141.],
        [184.],
        [152.],
        [148.],
        [192.],
        [147.],
        [183.],
        [177.],
        [159.],
        [177.],
        [175.],
        [175.],
        [149.],
        [192.]])

In [ ]:
print(x_data.shape)
print(len(x_data))
print(x_data[:5])

torch.Size([25, 3])
25
tensor([[ 73.,  80.,  75.],
        [ 93.,  88.,  93.],
        [ 89.,  91.,  90.],
        [ 96.,  98., 100.],
        [ 73.,  66.,  70.]])


In [ ]:
print(y_data.shape)
print(len(y_data))
print(y_data[:5])

torch.Size([25, 1])
25
tensor([[152.],
        [185.],
        [180.],
        [196.],
        [142.]])


In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim


In [ ]:
#reproducibility
torch.manual_seed(1)

In [ ]:
#Low_level implementation
#data
x_train=torch.FloatTensor(x_data)
y_train=torch.FloatTensor(y_data)
#initialize model
W=torch.zeros((3,1),requires_grad=True)
b=torch.zeros(1,requires_grad=True)
#set the optimizer
optimizer=optim.SGD([W,b],lr=1e-5)
nb_epochs=20
for epoch in range(nb_epochs+1):
#calculate H(x)
    hypothesis=x_train.matmul(W)+b
#calculate cost
    cost=torch.mean((hypothesis-y_train)**2)
#cost approach to H(x)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
#print epoch and cost
    print('Epoch:{:4d}/{}, Cost:{:.6f}'.format(epoch,nb_epochs,cost.item()))


Epoch:   0/20, Cost:26811.960938
Epoch:   1/20, Cost:9920.529297
Epoch:   2/20, Cost:3675.298828
Epoch:   3/20, Cost:1366.260742
Epoch:   4/20, Cost:512.542480
Epoch:   5/20, Cost:196.896698
Epoch:   6/20, Cost:80.190964
Epoch:   7/20, Cost:37.038689
Epoch:   8/20, Cost:21.081343
Epoch:   9/20, Cost:15.178769
Epoch:  10/20, Cost:12.993664
Epoch:  11/20, Cost:12.183025
Epoch:  12/20, Cost:11.880554
Epoch:  13/20, Cost:11.765974
Epoch:  14/20, Cost:11.720855
Epoch:  15/20, Cost:11.701433
Epoch:  16/20, Cost:11.691517
Epoch:  17/20, Cost:11.685120
Epoch:  18/20, Cost:11.679997
Epoch:  19/20, Cost:11.675385
Epoch:  20/20, Cost:11.670950


In [ ]:
#High level implementation with nn.Module
class MultivariateLinearRegressionModel(nn.Module):
      def __init__(self):
          super().__init__()
          self.linear = nn.Linear(3,1)

      def forward(self,x):
          return self.linear(x)


In [ ]:
#data
x_train=torch.FloatTensor(x_data)
y_train=torch.FloatTensor(y_data)
#initialize model
model=MultivariateLinearRegressionModel()
#set the optimizer
optimizer=optim.SGD(model.parameters(),lr=1e-5)
nb_epochs=20
for epoch in range(nb_epochs+1):
#calculate H(x)
    hypothesis=model(x_train)
#calculate cost
    cost=F.mse_loss(hypothesis,y_train)
#cost approach to H(x)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
#print epoch and cost
    print('Epoch:{:4d}/{}, Cost:{:.6f}'.format(epoch,nb_epochs,cost.item()))


Epoch:   0/20, Cost:13355.742188
Epoch:   1/20, Cost:4942.361328
Epoch:   2/20, Cost:1831.702515
Epoch:   3/20, Cost:681.604736
Epoch:   4/20, Cost:256.381622
Epoch:   5/20, Cost:99.164520
Epoch:   6/20, Cost:41.036831
Epoch:   7/20, Cost:19.545074
Epoch:   8/20, Cost:11.598702
Epoch:   9/20, Cost:8.660445
Epoch:  10/20, Cost:7.573805
Epoch:  11/20, Cost:7.171782
Epoch:  12/20, Cost:7.022855
Epoch:  13/20, Cost:6.967517
Epoch:  14/20, Cost:6.946784
Epoch:  15/20, Cost:6.938843
Epoch:  16/20, Cost:6.935635
Epoch:  17/20, Cost:6.934161
Epoch:  18/20, Cost:6.933359
Epoch:  19/20, Cost:6.932774
Epoch:  20/20, Cost:6.932291
