<a href="https://colab.research.google.com/github/eunjoo-ny/ML-Code/blob/main/PyTorch_Lab_01_1_Tensor_Manipulation1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import os
import torch
import torchvision
import tarfile
from torchvision.datasets.utils import download_url
from torch.utils.data import random_split

In [ ]:
import numpy as np
t=np.array([0.,1.,2.,3.,4.,5.,6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [ ]:
print('Rank of t:',t.ndim)
print('Shape of t:',t.shape)

Rank of t: 1
Shape of t: (7,)


In [ ]:
print('t[0]={},t[1]={},t[2]={}'.format(t[0],t[1],t[2]))
print('t[2:5]={},t[4:-1]={}'.format(t[2:5],t[4:-1]))
print('t[:2]={},t[3:]={}'.format(t[:2],t[3:]))


t[0]=0.0,t[1]=1.0,t[2]=2.0
t[2:5]=[2. 3. 4.],t[4:-1]=[4. 5.]
t[:2]=[0. 1.],t[3:]=[3. 4. 5. 6.]


In [ ]:
t1=np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
t1

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [ ]:
print('Rank of t1:',t1.ndim)
print('Shape of t1:',t1.shape)

Rank of t1: 2
Shape of t1: (4, 3)


1D Array with Pytorch


In [ ]:
t=torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [ ]:
print(t.dim())
print(t.shape)
print(t.size())
print(t[0],t[1],t[-1])
print(t[2:5],t[4:-1])
print(t[:2],t[3:])

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [ ]:
m1=torch.FloatTensor([[3,3]])
m2=torch.FloatTensor([[2,2]])
m1+m2

tensor([[5., 5.]])

In [ ]:
#vector+scalar
m1=torch.FloatTensor([[2,3]])
m2=torch.FloatTensor([2])
m1+m2

tensor([[4., 5.]])

In [ ]:
#2X1 Vector +1X2 Vector
m1=torch.FloatTensor([[3],[4]])
m2=torch.FloatTensor([[2,1]])
m1+m2

tensor([[5., 4.],
        [6., 5.]])

In [ ]:
print('-----------')
print('Mul vs Matmul')
print('-----------')
m1=torch.FloatTensor([[1,2],[3,4]])
m2=torch.FloatTensor([[1],[2]])
t=m1.matmul(m2)
print('Shape of Matrix 1 :',m1.shape)
print('Shape of Matrix 2 :',m2.shape)
print(t)
print('Shape of Matrix 1 :',m1.shape)
print('Shape of Matrix 2 :',m2.shape)
print(m1*m2)
print(m1.mul(m2))

-----------
Mul vs Matmul
-----------
Shape of Matrix 1 : torch.Size([2, 2])
Shape of Matrix 2 : torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of Matrix 1 : torch.Size([2, 2])
Shape of Matrix 2 : torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [ ]:
t=torch.FloatTensor([[1,2]])
t.mean()

tensor(1.5000)

In [ ]:
t=torch.LongTensor([[1,2]])
try:
  print(t.mean())
except Exception as exc:
  print(exc)

Can only calculate the mean of floating types. Got Long instead.


In [ ]:
t=torch.FloatTensor([[1,2],[3,4]])
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [ ]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [ ]:
t=torch.FloatTensor([[1,2],[3,4]])
t.max()

tensor(4.)

In [ ]:
print(t.max(dim=0))

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [ ]:
print('Max:',t.max(dim=0)[0])
print('ArgMax:',t.max(dim=0)[1])

Max: tensor([3., 4.])
ArgMax: tensor([1, 1])


In [ ]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


In [ ]:
t=np.array([[[1,2,3],
            [4,5,6]],
            [[7,8,9],
            [10,11,12]]])
ft=torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [ ]:
print(ft.view([-1,3]))
print(ft.view([-1,3]).shape)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
torch.Size([4, 3])


In [ ]:
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)

tensor([[[ 1.,  2.,  3.]],

        [[ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.]],

        [[10., 11., 12.]]])
torch.Size([4, 1, 3])


In [ ]:
ft=torch.Tensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [ ]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [ ]:
ft.view(1,-1),ft.view(1,-1).shape

(tensor([[0., 1., 2.]]), torch.Size([1, 3]))

In [ ]:
ft.unsqueeze(1),ft.unsqueeze(1).shape

(tensor([[0.],
         [1.],
         [2.]]), torch.Size([3, 1]))

In [ ]:
ft.unsqueeze(-1), ft.unsqueeze(-1).shape

(tensor([[0.],
         [1.],
         [2.]]), torch.Size([3, 1]))

In [ ]:
lt=torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [ ]:
lt.float()

tensor([1., 2., 3., 4.])

In [ ]:
bt=torch.ByteTensor([True,False,False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [ ]:
bt.long(),bt.float()

(tensor([1, 0, 0, 1]), tensor([1., 0., 0., 1.]))

In [ ]:
x=torch.FloatTensor([[1,2],[3,4]])
y=torch.FloatTensor([[5,6],[7,8]])

In [ ]:
torch.cat([x,y],dim=0),torch.cat([x,y],dim=1)


(tensor([[1., 2.],
         [3., 4.],
         [5., 6.],
         [7., 8.]]), tensor([[1., 2., 5., 6.],
         [3., 4., 7., 8.]]))

In [ ]:
x=torch.FloatTensor([1,4])
y=torch.FloatTensor([2,5])
z=torch.FloatTensor([3,6])

In [ ]:
torch.stack([x,y,z]), torch.stack([x,y,z],dim=1)

(tensor([[1., 4.],
         [2., 5.],
         [3., 6.]]), tensor([[1., 2., 3.],
         [4., 5., 6.]]))

In [ ]:
torch.cat([x.unsqueeze(0), y.unsqueeze(0),z.unsqueeze(0)],dim=0)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [ ]:
x=torch.FloatTensor([[0,1,2],[3,4,5]])
print(x)


tensor([[0., 1., 2.],
        [3., 4., 5.]])


In [ ]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
x=torch.FloatTensor([[1,2],[3,4]])

In [ ]:
print(x.mul(2.))

tensor([[2., 4.],
        [6., 8.]])


In [ ]:
print(x)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
x.mul_(2.)

tensor([[2., 4.],
        [6., 8.]])

In [ ]:
print(x)

tensor([[2., 4.],
        [6., 8.]])


In [ ]:
x_train=torch.FloatTensor([[1],[2],[3]])
y_train=torch.FloatTensor([[2],[4],[6]])
w=torch.zeros(1,requires_grad=True)
b=torch.zeros(1,requires_grad=True)
hypothesis= x_train*w+b
cost=torch.mean((hypothesis-y_train)**2)

In [ ]:
import torch.nn as nn 
import torch 
import torch.optim as optim 

In [ ]:
optimizer =optim.SGD([w,b],lr=0.01)

optimizer.zero_grad()
cost.backward()
optimizer.step()

In [ ]:
x_train=torch.FloatTensor([[1],[2],[3]])
y_train=torch.FloatTensor([[1],[2],[3]])
w=torch.zeros(1,requires_grad=True)
b=torch.zeros(1,requires_grad=True)
optimizer =optim.SGD([w,b],lr=0.01)

nb_epochs =1000
for epoch in range(1,nb_epochs+1):
    hypothesis= x_train*w+b
    cost=torch.mean((hypothesis-y_train)**2)


    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

In [ ]:
gradient = 2*torch.mean((w*x_train-y_train)*x_train)
lr=0.1
w =w-lr*gradient

In [ ]:
x_train=torch.FloatTensor([[1],[2],[3]])
y_train=torch.FloatTensor([[1],[2],[3]])

w=torch.zeros(1)
lr=0.1

nb_epochs=20
for epoch in range(nb_epochs+1):
    
    hypothesis= w*x_train
    cost=torch.mean(hypothesis-y_train)**2

    gradient=torch.sum(( hypothesis-y_train)*x_train)

    print('Epoch:{:4d}/{}, w:{:.3f} ,cost:{:.6f}'.format(epoch,nb_epochs,w.item(),cost.item()))

    w=w-lr*gradient

Epoch:   0/20, w:0.000 ,cost:4.000000
Epoch:   1/20, w:1.400 ,cost:0.640000
Epoch:   2/20, w:0.840 ,cost:0.102400
Epoch:   3/20, w:1.064 ,cost:0.016384
Epoch:   4/20, w:0.974 ,cost:0.002621
Epoch:   5/20, w:1.010 ,cost:0.000419
Epoch:   6/20, w:0.996 ,cost:0.000067
Epoch:   7/20, w:1.002 ,cost:0.000011
Epoch:   8/20, w:0.999 ,cost:0.000002
Epoch:   9/20, w:1.000 ,cost:0.000000
Epoch:  10/20, w:1.000 ,cost:0.000000
Epoch:  11/20, w:1.000 ,cost:0.000000
Epoch:  12/20, w:1.000 ,cost:0.000000
Epoch:  13/20, w:1.000 ,cost:0.000000
Epoch:  14/20, w:1.000 ,cost:0.000000
Epoch:  15/20, w:1.000 ,cost:0.000000
Epoch:  16/20, w:1.000 ,cost:0.000000
Epoch:  17/20, w:1.000 ,cost:0.000000
Epoch:  18/20, w:1.000 ,cost:0.000000
Epoch:  19/20, w:1.000 ,cost:0.000000
Epoch:  20/20, w:1.000 ,cost:0.000000


In [ ]:
x_train=torch.FloatTensor([[73,80,756],
                           [93,88,93],
                           [89,91,90],
                           [96,98,100],
                           [73,66,70]])
y_train=torch.FloatTensor([[152],[185],[180],[196],[142]])

In [ ]:
w=torch.zeros((3,1),requires_grad=True)
b=torch.zeros(1,requires_grad=True)
optimizer=optim.SGD([w,b],lr=1e-5)

nb_epochs=20
for epoch in range(nb_epochs+1):
    hypothesis=x_train.matmul(w)+b
    cost=torch.mean((hypothesis-y_train)**2)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch:{:4d}/{}, hypothesis:{}, cost:{:.6f}'.format(epoch,nb_epochs,hypothesis.squeeze().detach(),
                                                              cost.item()))
    # why does the cost fluctuate or increase?

Epoch:   0/20, hypothesis:tensor([0., 0., 0., 0., 0.]), cost:29661.800781
Epoch:   1/20, hypothesis:tensor([582.7939, 119.3461, 116.9166, 128.1442,  90.6439]), cost:40223.035156
Epoch:   2/20, hypothesis:tensor([-341.9339,   -1.6264,   -0.4172,   -1.9566,   -0.5123]), cost:74169.406250
Epoch:   3/20, hypothesis:tensor([1040.1355,  233.2516,  228.8514,  250.3842,  177.3696]), cost:159541.593750
Epoch:   4/20, hypothesis:tensor([-1092.8326,   -83.8484,   -79.7352,   -90.4602,   -62.2039]), cost:362621.750000
Epoch:   5/20, hypothesis:tensor([2142.4595,  434.0266,  425.1097,  466.0365,  329.5953]), cost:838426.750000
Epoch:   6/20, hypothesis:tensor([-2810.8074,  -328.3290,  -317.3936,  -353.2940,  -246.7532]), cost:1948397.625000
Epoch:   7/20, hypothesis:tensor([4734.6782,  857.9997,  838.6137,  921.5924,  650.4751]), cost:4534534.000000
Epoch:   8/20, hypothesis:tensor([-6790.7783,  -933.4818,  -906.6185, -1003.7035,  -704.1505]), cost:10557834.000000
Epoch:   9/20, hypothesis:tensor([

In [ ]:
import torch.nn as nn
class MultivaritateLinearRegression(nn.Module):
      def __init__(self):
          super().__init__()
          self.linear=nn.Linear(3,1)

      def forward(self,x):
          return self.linear(x)




In [ ]:
import torch.nn.functional as F
model=MultivaritateLinearRegression()
optimizer=optim.SGD([w,b],lr=1e-5)

nb_epochs=20
for epoch in range(nb_epochs+1):
    hypothesis=model(x_train)
    cost=F.mse_loss(hypothesis, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch:{:4d}/{}, hypothesis:{}, cost:{:.6f}'.format(epoch,nb_epochs,hypothesis.squeeze().detach(),
                                                              cost.item()))

Epoch:   0/20, hypothesis:tensor([-219.4243,    0.5513,    2.5822,    1.7929,    0.2766]), cost:52251.261719
Epoch:   1/20, hypothesis:tensor([-219.4243,    0.5513,    2.5822,    1.7929,    0.2766]), cost:52251.261719
Epoch:   2/20, hypothesis:tensor([-219.4243,    0.5513,    2.5822,    1.7929,    0.2766]), cost:52251.261719
Epoch:   3/20, hypothesis:tensor([-219.4243,    0.5513,    2.5822,    1.7929,    0.2766]), cost:52251.261719
Epoch:   4/20, hypothesis:tensor([-219.4243,    0.5513,    2.5822,    1.7929,    0.2766]), cost:52251.261719
Epoch:   5/20, hypothesis:tensor([-219.4243,    0.5513,    2.5822,    1.7929,    0.2766]), cost:52251.261719
Epoch:   6/20, hypothesis:tensor([-219.4243,    0.5513,    2.5822,    1.7929,    0.2766]), cost:52251.261719
Epoch:   7/20, hypothesis:tensor([-219.4243,    0.5513,    2.5822,    1.7929,    0.2766]), cost:52251.261719
Epoch:   8/20, hypothesis:tensor([-219.4243,    0.5513,    2.5822,    1.7929,    0.2766]), cost:52251.261719
Epoch:   9/20, hypo